version: '2.0'

services:
  waterfall_frontend:
    container_name: waterfall_web
    build: ./nodejs
    depends_on:
      - waterfall_backend
    links:
      - waterfall_backend
    ports:
      - "18000:3000"

  waterfall_backend:
    container_name: waterfall_server
    build: ./
    cap_add:
      - SYS_NICE
    devices:
      - /dev/bus/usb
    entrypoint:
      - "python"
      - "server.py"
      - "--sample-rate"
      - "20e6"
      - "--frequency"
      - "777e6"
      - "--gain"
      - "40"
      - "--fft-size"
      - "4096"
      - "--frame-rate"
      - "25"